#!/usr/bin/env bash
#
# Name:         fftunnel
#
# Purpose:      super easy encrypted browsing
#    
# Comments:     uses a Firefox settings profile configured for SOCKS5 
#
# Author:       Amin Astaneh (amin@aminastaneh.net)
#
# License Information
#
# Copyright (C) 2012 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FORWARDING_PORT=9999

if [[ -z "${1}" ]]; then
	echo "Usage: $0 user@hostname <other_options>"
	exit 1
fi

ssh -ND $FORWARDING_PORT $@ &
PID=$!
firefox -P Secure
kill $PID
